# Generated by Django 5.2.7 on 2025-10-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
