# Generated by Django 5.2.7 on 2025-10-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photoUrl',
        ),
    ]
