# Generated by Django 5.2.7 on 2025-10-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='post',
        ),
    ]
